package com.stevecorp.codecontest.hashcode.facilitator.configurator.algorithm;

import com.stevecorp.codecontest.hashcode.facilitator.configurator.input.InputModel;
import com.stevecorp.codecontest.hashcode.facilitator.configurator.output.OutputModel;

public interface Algorithm<T extends InputModel, U extends OutputModel> {

    /**
     * The method that solves the problem statement for a given input.
     *
     * @param input the input for the algorithm
     * @return the output generated by the algorithm
     */
    U solve(T input);

}
